In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/PO_norm_analysed_16may.csv", index_col = 0)
df = df.loc[~(df['ID'].isin(['BH4', 'UCR243', 'UCR102']))]
df = df.loc[df['Binding_validated_by_TSA'] == 'strong_evidence']
df.head()

/var/folders/g9/1n3d85nn2d14mq2r60k26ddc0000gn/T/ipykernel_14438/1407379470.py:1: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data/PO_norm_analysed_16may.csv", index_col = 0)

,ID,Cxsmiles,Formula,MW,Purity,PO,Salt smiles,Salt_name,Salt_ratio,MW_salt,...,SpSh_qval,bind_pval,bind_qval,bind_combined,bind_and_stabilize,bind_and_destabilize,bind_and_stabilize_weak,bind_and_destabilize_weak,bind_tsa,Binding_validated_by_TSA
6,CSCS00133028662,CC1=NN(C=C1CNC2[C@@H]3CCO[C@@H]3C2(C)C)C=4C=CC...,C19H25N3O,311.4213,98.01,ini2810,NaN,NaN,NaN,0.0,...,1.0,True,False,weak_evidence,False,False,False,True,"('weak_evidence', 'no_evidence', 'strong_evide...",strong_evidence
12,CSCS00133087567,CC1=NON=C1C(=O)N[C@@H]2CCCN(C2)C(=O)C3=NON=C3C,C13H16N6O4,320.3039,94.04,ini2810,NaN,NaN,NaN,0.0,...,1.0,True,False,weak_evidence,False,False,False,True,"('weak_evidence', 'no_evidence', 'strong_evide...",strong_evidence
13,CSCS00102895036,O=C1NCCN1C2CN(C2)S(=O)(=O)C=3C=CC(F)=C(F)C3F,C12H12F3N3O3S,335.3022,100.00,ini2810,NaN,NaN,NaN,0.0,...,1.0,True,False,weak_evidence,False,False,True,False,"('weak_evidence', 'strong_evidence', 'no_evide...",strong_evidence
21,CSCS00133099652,O=C(CC1=CC=CO1)N2CCCC=3C=C(Cl)C=NC32,C14H13ClN2O2,276.7182,92.95,ini2810,NaN,NaN,NaN,0.0,...,1.0,True,False,weak_evidence,False,False,False,True,"('weak_evidence', 'no_evidence', 'strong_evide...",strong_evidence
25,CSCS00027148854,CC1=CC=C(O1)C(=O)NC2CCN(CC2)C=3C=CC(Cl)=C(C#N)N3,C17H17ClN4O2,344.7955,92.77,ini2810,NaN,NaN,NaN,0.0,...,1.0,True,False,weak_evidence,False,False,False,True,"('weak_evidence', 'no_evidence', 'strong_evide...",strong_evidence

In [3]:
df['Protein'].unique()

array(['PAH-WT', 'failed', 'PAH-I65T'], dtype=object)

In [4]:
bind_id_wt = df.loc[df['Protein'] == 'PAH-WT', 'ID']
bind_id_mut = df.loc[df['Protein'] == 'PAH-I65T', 'ID']
# bind_id_wt, bind_id_mut

In [5]:
intersection = list(set(bind_id_wt).intersection(set(bind_id_mut)))

In [6]:
len(intersection)

1687

In [7]:
df_intersection = pd.DataFrame({'intersection'  : intersection})
df_intersection

         intersection
0     CSCS00026049138
1     CSCS00102894870
2     CSCS00133039246
3     CSCS00028121210
4     CSCS00028239464
...               ...
1682  CSCS00026130661
1683  CSCS00133105277
1684  CSCS00027021789
1685  CSCS00027248530
1686  CSCS00027857057

[1687 rows x 1 columns]

In [8]:
df_intersection.to_csv("/Users/behnam/Desktop/id_intersection_strong_PAH_WT_I65T.csv")